# Configuration for image captioning model
hyperparams:
  # Choose encoder type: "cnn" or "hierarchical_cnn_vit"
  encoder_type: hierarchical_cnn_vit
  
  # Parameters for original CNN encoder (used when encoder_type is "cnn")
  image_encoder:
    encode_size: 14  # Size of feature grid (14×14)
    embed_dim: 512   # Feature dimension
  
  # Parameters for hierarchical CNN-ViT encoder
  hierarchical_encoder:
    encode_size: 14            # Size of feature grid
    embed_dim: 512             # Feature dimension
    num_heads: 8               # Number of attention heads
    depth: 6                   # Number of transformer layers
    dropout: 0.1               # Dropout rate
    use_efficientnet: true     # Whether to use EfficientNet (false for ResNet)
    backbone_name: efficientnet_b3  # IMPORTANT: This is the source of truth for backbone model
    # Backbone feature dimensions:
    # EfficientNet-B3: [40, 112, 384]
    # EfficientNet-B4: [48, 136, 448]
    
    # Custom projection dimensions - set this if loading from a checkpoint with different dimensions
    # projection_dims: [40, 112, 384]  # Uncomment and set to match checkpoint dimensions
  
  # Parameters for transformer decoder
  transformer:
    d_model: 512               # Model dimension
    enc_ff_dim: 512            # Encoder feed-forward dimension
    dec_ff_dim: 2048           # Decoder feed-forward dimension
    enc_n_layers: 2            # Number of encoder layers
    dec_n_layers: 4            # Number of decoder layers
    enc_n_heads: 8             # Number of encoder attention heads
    dec_n_heads: 8             # Number of decoder attention heads
    dropout: 0.1
    use_enhanced_decoder: true # Whether to use enhanced decoder with cross-attention

# Training parameters
train_parms:
  epochs: 60
  val_interval: 1
  early_stop: 10
  lr_patience: 3
  embedings_finetune: 10
  enable_finetune: false
  grad_clip: 0.1
  lambda_c: 1.0
  use_wandb: true
  project_name: vit-cnn-large

# Dataloader parameters
dataloader_parms:
  batch_size: 32
  shuffle: true
  num_workers: 4

# Paths for data and checkpoints
pathes:
  checkpoint: ./checkpoints_vit_cnn

# Optimizer parameters
optim_params:
  encoder_lr: 1.0e-4
  transformer_lr: 1.0e-4
  lr_factors: [0.8, 0.8]

# Debug settings
debug:
  enabled: false
  max_samples: 100

# Other parameters
seed: 9001
max_len: 52
min_freq: 2